Universidade Federal do Rio Grande do Sul (UFRGS)   
Programa de Pós-Graduação em Engenharia Civil (PPGEC)   

# PEC00144: Experimental Methods in Civil Engineering


### Part I: Analysis
[1.   Dimensional analysis and similarity](#section_1)   
[1.1. Quantities, units, dimensions](#section_11)   
[1.2. Dataframe for scales computation](#section_12)   
[1.3. The Theorem of Pi's by Vaschy-Buckinghan](#section_13)   
[1.4. Change of units and change of scales](#section_14)  
[1.5. Famous Pi-Numbers](#section_15)  


[2.   Reduced scale models](#section_2)   
[2.1. Controlled and derived scales](#section_21)   
[2.2. Example: elastic beam under self weight](#section_22)   
[2.3. Example: aeroelastic model of a slender tower](#section_23)   
[2.4. Example: cable catenary](#section_24)   

---
_Prof. Marcelo M. Rocha, Dr.techn._ [(ORCID)](https://orcid.org/0000-0001-5640-1020)  
_Porto Alegre, RS, Brazil_ 


In [3]:
# Importing Python modules required for this notebook
# (this cell must be executed with "shift+enter" before any other Python cell)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## 1. Dimensional analysis and similarity <a name="section_1"></a> 

### 1.1. Quantities, units, dimensions  <a name="section_11"></a> 

Prof. G.I. Barenblatt has written in his book _Dimensional Analysis_ (1987):   

>_In fact, the idea on which dimensional analysis is based is very simple, and can be 
understood by all: physical laws do not depend on arbitrariness in the choice of basic 
units of measurement. An important conclusion can be drawn from this simple idea 
using simple arguments: the functions that express physical laws must possess a 
certain fundamental property, which in mathematics is called generalized homogeneity 
or symmetry. This property allows the number of arguments in these functions to be 
reduced, thereby making it simpler to obtain them (by calculating them or determining 
them experimentally). This is, in fact, the entire content of dimensional analysis - there 
is nothing more to it._

In other words, the units resulting from both sides of an equation must be the same.
Although simple, this idea has allowed great scientists like Newton, Rayleigh, Maxwell, 
Reynolds, Kolmogorov, Cauchy, and many others, to proposed many fundamental 
physical principles.

To illustrate how the law of _dimensional homogeneity_ can be applied, let us 
investigate the free vibration frequency, $f_{\rm n}$, of an undamped mass-spring 
system with one degree of freedom.

<img src="resources/figSDOF.jpg" alt="figSDOF" width="360px"/>

The frequency $f_{\rm n}$ could be derived from mechanical principles like dynamic
equilibrium equations, but we take the alternative dimensional path instead.
The system above _may_ involve several physical quantities like: 

* the instantaneous position, $u$,   
* the oscillating mass, $m$,   
* the time, $t$,   
* the displacement amplitude, $u_0$,   
* the spring linear stiffness, $k$, and finally   
* the free vibration frequency, $f_{\rm n}$.  

The completeness of this set of quantities is essential for the success of our
dimensional analysis. The analysis process requires an investigation of possible
relationships among the _candidate_ quantities above and the frequency $f_{\rm n}$. 
Let us take a look at their _units of measurement_: 

\begin{align*}
[ u ]        &= [L]^{1}[M]^{0}[T]^{0}  \\
[ m ]        &= [L]^{0}[M]^{1}[T]^{0}  \\
[ t ]        &= [L]^{0}[M]^{0}[T]^{1}  \\
[ u_0 ]      &= [L]^{1}[M]^{0}[T]^{0}  \\
[ k ]        &= [L]^{0}[M]^{1}[T]^{-2} \\
[ f_{\rm n}] &= [L]^{0}[M]^{0}[T]^{-1}
\end{align*}

where the brackets mean "units of". One can observe that all measurement units have been
written in terms of only three _fundamental units_: length, $[L]$, mass, $[M]$, and time, $[T]$. 
Most principles in solid mechanics and structural dynamics may be expressed with these 
three units only. Eventually the temperature, $\Theta$, may be needed.
For the sake of simplicity, hereafter brackets will be ommited.

The quantities directly subordinated to the fundamental units are called _fundamental
quantities_, which are the length, the mass and the time, while other units and quantities
are called _derived units and quantities_, like stiffness, frequency, speed, etc. 
The dependency of derived units on the fundamental are expressed through dimensional formulae,
as shown above, which are _always power-law monomials_. The exponents applyed to the 
fundamental units in these formulae are called _dimension_ or _dimension exponent_.

In the case of using the _International System_ (SI), the three fundamental units are the
meter (m), the kilogram (kg), and the second (s). In the example above this means that:

\begin{align*}
[ u ]        &= {\rm m}^{1}{\rm kg}^{0}{\rm s}^{0} = {\rm m}  \\
[ m ]        &= {\rm m}^{0}{\rm kg}^{1}{\rm s}^{0} = {\rm kg} \\
[ t ]        &= {\rm m}^{0}{\rm kg}^{0}{\rm s}^{1} = {\rm s}  \\
[ u_0 ]      &= {\rm m}^{1}{\rm kg}^{0}{\rm s}^{0} = {\rm m}  \\
[ k ]        &= {\rm m}^{0}{\rm kg}^{1}{\rm s}^{-2} = {\rm kg}/{\rm s}^{2} = {\rm N/m} \\
[ f_{\rm n}] &= {\rm m}^{0}{\rm kg}^{0}{\rm s}^{-1} = 1/{\rm s} = {\rm Hz}
\end{align*}

### 1.2. Dataframe for scales computation  <a name="section_12"></a> 

To facilitate the scales calculations as presented in this _notebook_, let us now import 
a ```pandas``` dataframe with physical quantities commonly used in engineering mechanics and
structural dynamics, aerodynamics, and fluid and soil mechanics:

In [4]:
DimData = pd.read_excel('resources/DimData.xlsx')

print(DimData)

                         descriptor  L  M  T
a                      Acceleration  1  0 -2
alpha          Angular acceleration  0  0 -2
omega             Angular frequency  0  0 -1
A                              Area  2  0  0
EI           Beam bending stiffness  0  1 -2
GAs            Beam shear stiffness  2  1 -2
rho                         Density -3  1  0
mu                Dynamic viscosity -1  1 -1
F                             Force  1  1 -2
f                         frequency  0  0 -1
nu              Kinematic viscosity  2  0 -1
L                            Length  1  0  0
m                              Mass  0  1  0
im     Mass inertia per unit length  1  1  0
mA               Mass per unit area -2  1  0
mL             Mass per unit length -1  1  0
M                            Moment  2  1 -2
I                 Moment of inertia  4  0  0
W                 Resistent modulus  3  0  0
Im          Rotational mass inertia  2  1  0
k                  Spring stiffness  0  1 -2
sigma     

Other quantities may be easily included in this dataframe by editing the Excel file
```DimData.xlsx```. Each entry in the table corresponds to a dimensional quantity, being the last
three columns the respective dimension exponents in the dimensional formulae.
Quantities like angles, strains, Poison's coefficient and ratio of critical damping are
by definition non-dimensional, so there is no need of including them in that table.
Relations between length measures, the so-called _form factors_, must also not be included.

To access the $LMT$ exponents of a set of quantities, let us say the length, $L$, 
the acceleration, $a$, and the density, $\rho$, the dataframe ```loc``` view may be used:

In [5]:
param = ['L', 'a', 'rho']    # selected parameters
LMT   = ['L', 'M', 'T'  ]    # three last columns of dataframe

P_LMT = DimData.loc[param, LMT].values

print(P_LMT)

[[ 1  0  0]
 [ 1  0 -2]
 [-3  1  0]]


The ```values``` property must be called to provide the information as a ```numpy``` array.
This array will be required in the following sections, where we show how the information provided in the dataframe  ```DimData``` can be used to carry out units and scales changes for designing reduced scale models.

The dataframe indices are the codes to access a specific quantity, while the following first column,
which header is ```descriptor```, corresponds to a description to help identification:

In [6]:
print(DimData.index)

Index(['a', 'alpha', 'omega', 'A', 'EI', 'GAs', 'rho', 'mu', 'F', 'f', 'nu',
       'L', 'm', 'im', 'mA', 'mL', 'M', 'I', 'W', 'Im', 'k', 'sigma', 't', 'v',
       'c', 'V'],
      dtype='object')


In [7]:
print(DimData.loc[param, 'descriptor'])

L            Length
a      Acceleration
rho         Density
Name: descriptor, dtype: object


### 1.3. O Teorema dos Pi's de Vaschy-Buckinghan  <a name="section_13"></a> 

O _Teorema dos $Pi$'s de Vaschy-Buckingham_ pode ser enunciado da seguinte forma:

>Dado um processo físico envolvendo $n$ _grandezas dimensionais_, denotadas como $p_1, p_2, \dots, p_n$. Pode-se expressar matematicamente este processo por meio da relação geral:<br><br>
\begin{equation}
 f\left (  p_1, p_2, \dots, p_n \right ) = 0 
\end{equation}<br>
>Esta relação pode ser substituída por outra relação entre $r = n - k$ _parâmetros adimensionais_:<br><br>
\begin{equation}
 F\left (  \Pi_1, \Pi_2, \dots, \Pi_r \right ) = 0
\end{equation}<br>
onde $k$ é o número de unidades fundamentais necessárias para compor as unidades das grandezas dimensionais. Os números $\Pi$ tem a seguinte forma:<br><br>
\begin{equation}
\Pi_i = p_1^{\alpha_1} \; p_2^{\alpha_2} \; \dots \; p_n^{\alpha_n}
\end{equation}<br>
onde os expoentes $\vec{\alpha} = \left [ \alpha_1 \; \alpha_2 \; \dots \; \alpha_n \right ]^{\rm T}$ sejam tais que a condição de adimensionalidade seja resguardada.

Considerando-se apenas as unidades fundamentais $L$, $M$, $T$, no presente contexto tem-se $k = 3$. A demonstração deste teorema é facilmente encontrada na literatura e não será reproduzida aqui. 

Para a aplicação do teorema, pode-se formar uma _matriz dimensional_, $\bf M$, cujas linhas são os expoentes, ou _dimensões_, das grandezas fundamentais compondo as unidades de todos os parâmetros envolvidos. Para a construção dos números $\Pi$, buscam-se vetores (coluna),  $\vec{\alpha}$, tal que (com $k = 3$): 

\begin{equation}
{\bf M} \vec{\alpha} = \left [ \begin{array}{ccc}
                                0 \\
                                0 \\
                                0
                               \end{array} \right ]
\end{equation}

Não existe uma regra geral para a determinação de $\vec{\alpha}$ e, portanto, dos respectivos números $\Pi$. O princípio prático que orienta a escolha desses adimensionais é o seu significado físico. 

No exemplo do oscilador mecânico apresentado anteriormente, admite-se existir relações matemáticas entre as grandezas envolvidas:

\begin{equation}
 f\left ( u, m, t, u_0, k, f_{\rm n} \right ) = 0 
\end{equation}

Neste caso a matriz dimensional seria, portanto:

In [11]:
param = ['L', 'm', 't', 'L', 'k', 'f']
M     =  DimData.loc[param, LMT].values.T

print(M)

[[ 1  0  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  1  0 -2 -1]]


Note that the transposition was called to impose the dimensions of matrix $\mathbf M$ according
to the previous definition (each column corresponds to a quantity).

Como já mencionado, quando se está investigando um processo ainda pouco compreendido, a escolha destas grandezas é apenas um palpite ilustre (_educated guess_, em inglês). O conjunto pode tanto exceder as necessidades como ser incompleto! A análise dimensional não deve ser vista como uma panacéia, mas sim como um possível caminho para se entender melhor (e com sorte completamente) o fenômeno investigado.

Possíveis números $\Pi$ para o conjunto de grandezas envolvidas no oscilador mecânico são:

\begin{equation}
 \Pi_1 = u^1 u_0^{-1},   \hspace{2cm}
 \Pi_2 = t^1 \; f_{\rm n}^{-1},  \hspace{2cm}
 \Pi_3 = m^{-1/2} \; k^{1/2} \; f_{\rm n}^{-1} 
\end{equation}

onde $\Pi_3$ é claramente o número mais interessante, com $\vec{\alpha}_3 = \left [ 0 \;\;\; {-1/2} \;\;\; 0 \;\;\;  0 \;\;\; 1/2  \;\;\; {-1} \right ]^{\rm T}$. Observe que o produto ${\bf M} \vec{\alpha}$ confirma a adimensionalidade:

In [12]:
a = np.array([0, -1/2, 0, 0, 1/2, -1]).reshape(6,1)

print(np.dot(M, a))

[[0.]
 [0.]
 [0.]]


A ideia de estabelecer relações entre números adimensionais implica uma independência do sistema de unidades adotado, mas não necessariamente uma independência de escala. Através de um programa experimental, os números $\Pi$ podem ser quantificados individualmente ou relacionados entre si, eventualmente conduzindo a modelos matemáticos que _independam_ da escala. 

No exemplo dado, através da equação diferencial de equilíbrio dinâmico de um oscilador mecânico pode-se demonstrar que $\Pi_3 = 2\pi$, ou seja, uma _constante_. O mesmo resultado poderia ter sido obtido experimentalmente, sem que se utilizassem quaisquer outros princípios físicos (equilíbrio, conservação de energia, etc.) mas apenas as dimensões das grandezas envolvidas, chegando-se finalmente a que:

$$f_{\rm n} = \frac{1}{2\pi} \sqrt{\frac{k}{m}} $$

Essa é a abordagem básica da análise dimensional, que permitiu que grandes cientistas apresentassem ao mundo números adimensionais que regem fenômenos importantes, tais como o número de Reynolds (forças de arrasto em corpos imersos em fluidos), de Froude (relação entre forças gravitacionais e inerciais), ou de Strouhal (frequência de desprendimento de vórtices alternados). 

### 1.4. Mudança de unidades de base e mudança de escala  <a name="section_14"></a> 

As fórmulas dimensionais permitem que se recalculem as unidades derivadas a partir de uma nova escolha das unidades de base. Esse cálculo pode ser usado para diversas finalidades, como por exemplo: (1) mudanças no sistema de unidades, como por exemplo do SI para o sistema britânico, ou (2) mudanças de escala das grandezas, para projeto de modelos reduzidos.

A escolha das grandezas $L$, $M$, e $T$ como grandezas de base é de certa forma arbitrária, embora esteja bem estabelecida internacionalmente. Contudo, é possível substituir essas três grandezas e logo obter uma nova matriz dimensional para outras três grandezas derivadas.

Supondo o estudo de um fenômeno qualquer na base $LMT$, no qual se deseje utilizar uma nova base composta pelas grandezas $A$, $B$ e $C$. A matriz dimensional da nova base é: 

\begin{align*}
 A &= L^{a_{L}} M^{a_{M}} T^{a_{T}} \\
 B &= L^{b_{L}} M^{b_{M}} T^{b_{T}} \\
 C &= L^{c_{L}} M^{c_{M}} T^{c_{T}}
\end{align*}

Por exemplo, chamando a função  ```dim_base``` para três novas grandezas de base, especificada como sendo formada por $A = L$ (comprimento),  $B = \mu$ (massa específica), e $C = g$ (aceleração da gravidade):

In [15]:
DB = DimData.loc[['L', 'a', 'rho'], ['L', 'M', 'T']].values

Observe que a definição matemática da matriz dimensional acima requer que a função ```dim_base``` retorne a matriz invertida em relação a função ```get_mat```. A função ```dim_base```, por definição, também não aceita mais do que três elementos na tupla de entrada.

Tomando-se o logaritmo de todos os termos da matriz dimensional tem-se:

\begin{align*}
\log A &= \log \left ( L^{a_{L}} M^{a_{M}} T^{a_{T}} \right ) = a_{L}\log L + a_{M}\log M + a_{T}\log T \\
\log B &= \log \left ( L^{b_{L}} M^{b_{M}} T^{b_{T}} \right ) = b_{L}\log L + b_{M}\log M + b_{T}\log T \\
\log C &= \log \left ( L^{c_{L}} M^{c_{M}} T^{c_{T}} \right ) = c_{L}\log L + c_{M}\log M + c_{T}\log T
\end{align*}

Na forma matricial:
\begin{equation}
\left [ \begin{array}{ccc}
         a_{L}& a_{M}& a_{T} \\
         b_{L}& b_{M}& b_{T} \\
         c_{L}& c_{M}& c_{T}
        \end{array} \right ]
\left [ \begin{array}{ccc}
        \log L \\
        \log M \\
        \log T
        \end{array} \right ] =
\left [ \begin{array}{ccc}
        \log A \\
        \log B \\
        \log C
        \end{array} \right ]
\end{equation}

onde se observa que a matriz do lado esquerdo da equação é a matriz dimensional da nova base. Isolando-se o vetor com as grandezas de base têm-se:

\begin{equation}
\left [ \begin{array}{ccc}
        \log L \\
        \log M \\
        \log T
        \end{array} \right ] =
\left [ \begin{array}{ccc}
         a_{A}& a_{B}& a_{C} \\
         b_{A}& b_{B}& b_{C} \\
         c_{A}& c_{B}& c_{C}
        \end{array} \right ]
\left [ \begin{array}{ccc}
        \log A \\
        \log B \\
        \log C
        \end{array} \right ]
\end{equation}

onde:

\begin{equation}
\left [ \begin{array}{ccc}
      a_{A}& a_{B}& a_{C} \\
      b_{A}& b_{B}& b_{C} \\
      c_{A}& c_{B}& c_{C}
     \end{array} \right ] =
\left [ \begin{array}{ccc}
      a_{L}& a_{M}& a_{T} \\
      b_{L}& b_{M}& b_{T} \\
      c_{L}& c_{M}& c_{T}
     \end{array} \right ] ^{-1}
\end{equation}

Voltando-se agora à forma monomial, chega-se a:

\begin{align*}
 L &= A^{a_{A}} B^{a_{B}} C^{a_{C}} \\
 M &= A^{b_{A}} B^{b_{B}} C^{b_{C}} \\
 T &= A^{c_{A}} B^{c_{B}} C^{c_{C}}
\end{align*}

Portanto, que para se obter a matriz dimensional das grandezas fundamentais em uma nova base basta inverter a matriz dimensional (transposta) desta nova base. Isso só é possível se essa matriz tem determinante positivo, ou seja, as grandezas que constituem a nova base devem ter expoentes de dimensão linearmente independentes entre si. Isso significa, por exemplo, que não se poderia escolher como novas grandezas de base a _velocidade_ (m/s), o _comprimento_ (m), e o _tempo_ (s), pois as unidades de uma das três grandezas pode se representada por uma relação entre as outras duas. Logo, a matriz dimensional não poderia ser invertida.

A inversão da matriz dimensional da nova base é feita em Python pelo módulo ```numpy``` como:

In [14]:
IDB = np.linalg.inv(DB)

print(IDB)

[[ 1.  -0.  -0. ]
 [ 3.   0.   1. ]
 [ 0.5 -0.5  0. ]]


Vejamos agora o que acontece com uma grandeza derivada, $X$, para a qual se deseje conhecer as dimensões na nova base. As dimensões na base $LMT$ são dadas por:

\begin{equation}
 X = L^{\alpha_{L}} M^{\beta_{M}} T^{\gamma_{T}}
\end{equation} 

e portanto:

\begin{equation}
 X = \left ( A^{a_{A}} B^{a_{B}} C^{a_{C}} \right )^{\alpha_{L}}
     \left ( A^{b_{A}} B^{b_{B}} C^{b_{C}} \right )^{\beta_{M}}
     \left ( A^{c_{A}} B^{c_{B}} C^{c_{C}} \right )^{\gamma_{T}} 
\end{equation}

Rearranjando-se os termos:

\begin{equation}
 X = A^{(a_{A}\alpha_{L} + b_{A}\beta_{M} + c_{A}\gamma_{T})}
     B^{(a_{B}\alpha_{L} + b_{B}\beta_{M} + c_{B}\gamma_{T})}
     C^{(a_{C}\alpha_{L} + b_{C}\beta_{M} + c_{C}\gamma_{T})}
   = A^{\alpha_{A}} B^{\beta_{B}} C^{\gamma_{C}}
\end{equation}

Observa-se que as dimensões na nova base podem ser calculadas com uma multiplicação matricial:

\begin{equation}
\left [ \begin{array}{ccc}
        \alpha_{A} \\
        \beta_{B} \\
        \gamma_{C}
        \end{array} \right ]  =
\left [ \begin{array}{ccc}
         a_{A}& a_{B}& a_{C} \\
         b_{A}& b_{B}& b_{C} \\
         c_{A}& c_{B}& c_{C}
        \end{array} \right ] ^{T} 
\left [ \begin{array}{ccc}
        \alpha_{L} \\
        \beta_{M} \\
        \gamma_{T}
        \end{array} \right ] 
\end{equation}

Com o módulo ```numpy``` essa multiplicação é feita da seguinte forma:

In [16]:
new_M = np.dot(IDB.T, M)

print(new_M)

[[ 1.   3.   0.5  1.   2.  -0.5]
 [ 0.   0.  -0.5  0.   1.   0.5]
 [ 0.   1.   0.   0.   1.   0. ]]


Como já mencionado, uma das aplicações da mudança de base é a mudança de unidades das grandezas fundamentais. A nova matriz dimensional nos permite calcular o efeito desta mudança nas grandezas derivadas. Por exemplo, vamos admitir que desejamos utilizar a milha nautica ao invés do metro como unidade de comprimento, e a hora ao invés do segundo como unidade do tempo. Vejamos como isso repercute na unidade de velocidade, sendo que a fórmula de cálculo é a mesma que foi anteriormente utilizada para a dimensão:

\begin{equation}
 X = A^{\alpha_{A}} B^{\beta_{B}} C^{\gamma_{C}}
\end{equation}


In [ ]:
L_length = 1/1852      # 1 nautical mile are 1852 meters
L_mass   = 1/1         # 1 kilogram will remain kilogram
L_time   = 1/3600      # 1 hour is 3600 seconds

print(L_speed)

ou seja, a nova unidade da velocidade é o nó (_1 knot = 1 mile/hour_) sendo que 1m/s (sistema SI) corresponde a aproximadamente 1.94 nós.

Outro aspecto interessante desse cálculo é que exatamente o mesmo procedimento pode ser utilizado para se modificar a escala de alguns parâmetros que descrevem um fenômeno físico, e conhecer a repercussão desta mudança em outros parâmetros relevantes. Esta é a ferramenta básica utilizada no projeto de modelos reduzidos, que será discutido na próxima seção.

Por exemplo, abaixo está o cálculo da nova escala de velocidade para uma mudança na escala de comprimento, $L$,  mantendo-se a escala de massa específica, $\mu$, e da aceleração da gravidade, $g$ inalteradas:

In [ ]:
L_length = 1/160      # escala de comprimento do modelo reduzido
L_dens   = 1/1        # density unchanged
L_accel  = 1/1        # acceleration unchanged

print(1/L_speed)

Ou seja, uma velocidade de 1m/s no modelo reduzido corresponde aproximadamente a 12.65m/s na escala real (também chamada de escala do protótipo), desde que o modelo reduzido respeite a escala 1:1 para a massa específica. 

### 1.5. Famous $\Pi$-numbers  <a name="section_15"></a> 

Um dos exemplos mais citados sobre uso de adimensionais para descrever fenômenos físicos é a relação entre o coeficiente de arrasto e o número de Reynolds no estudo do escoamento de fluidos em torno de corpos sólidos. O coeficiente de arrasto, $C_{\rm D}$, é uma relação entre a força de arrasto, $F_{\rm D}$ é a força aerodinâmica, $\rho V^2 A/2$, onde $\rho$ é a massa específica do fluido, $V$ é a velocidade do escoamento, e $A$ é a área exposta de referência (geralmente a seção perpendicular ao escoamento):

$$ C_{\rm D} = \frac{F_{\rm D}}{\frac{1}{2} \rho V^2 A}$$

Já o número de Reynolds representa uma relação entre as forças inerciais e as forças de viscosidade em um fluido, definido como:

$$ {\rm Re} = \frac{V \, D}{\nu}$$ 

onde $D$ é uma dimensão de referência da área exposta (perpendicular à direção do escoamento), e $\nu$ é a viscosidade cinemática do fluido ($\nu \approx 1.48 \times 10^5 {\rm m^2/s}$ para o ar na temperatura ambiente). A figura abaixo mostra o que resulta de uma investigação experimental da relação entre estes dois adimensionais para uma esfera.

<img src="resources/drag_coefficient.jpg" alt="drag_coefficient" width="600px"/>

Observa-se, neste caso, que a relação apresentada graficamente pode ser usada em qualquer escala, independentemente de existirem modelos preditivos baseados em princípios físicos. Aqui o fenômeno é descrito apenas em termos de adimensionais.


## 2. Reduced scale models <a name="section_2"></a> 

### 2.1. Controlled and uncontrolled quantities  <a name="section_21"></a> 



### 2.2. Example: elastic beam under self-weight  <a name="section_22"></a> 

Como exemplo, vamos projetar um modelo reduzido de uma viga de concreto armado com vão $L = 10$m submetida ao peso próprio, para a qual desejamos medir o deslocamento vertical no centro, $w_{\rm max}$. Vamos adotar uma escala de comprimento 1:10 e uma escala de aceleração 1:1, já que a mesma aceleração da gravidade estará atuando tanto sobre o modelo como sobre a estrutura real. 

<img src="resources/SimpleBeam.png" alt="SimpleBeam" width="480px"/>

* Seção transversal:    
  $B\times H = 0.3 \times 0.6 {\rm m}$    
  Portanto:    
  $A = 0.18 {\rm m}^2$ e $I = 0.0054 {\rm m}^4$ <br>
* Massa específica do concreto:    
  $\rho = 2500 {\rm kg/m}^3$    
  Portanto:    
  $q = \rho A g = 2500 \times 0.18 \times 9.81 \approx 4400 {\rm N/m}$ <br>
* Módulo de elasticidade do concreto:    
  $E_{\rm c} = 3 \times 10^{11} {\rm N/m}^2$   
  Portanto:    
  $E_{\rm c}I = 1.6 \times 10^6 {\rm Nm}^2$
 
<br>
Adicionalmente, vamos estabelecer que o modelo será construído em alumínio. Isso resulta numa escala para o módulo de elasticidade igual a 71GPa:205GPa, ou seja, 1:2.89. Com base nesta informação a matriz dimensional da nova base será dada por:


In [ ]:
DB =  dim_base(('length', 'accel', 'stress'));   print(DB)

E as escalas necessárias são:

In [ ]:
L_length =  1/10       # escala de comprimento do modelo reduzido
L_accel  =  1/1        # mesma gravidade
L_stress = 71/205      # módulo de Young


Se o modelo é para ser construído e utilizado em experimentos que respeitem plenamente a semelhança com a estrutura real é necessário que todos os demais parâmetros sejam respeitados, o que não é em geral possível.
Por exemplo, observa-se que a massa específica do modelo deve ser aproximadamente 16.5 vezes maior que a massa específica da estrutura real. Se isso não for respeitado, os deslocamentos sob peso próprio não respeitarão a escala de comprimento, ficando aquém dos valores corretos, e o modelo será inadequado para o propósito estabelecido. 


In [ ]:
L_load_L = new_scale('load_L', ('length', 'accel', 'stress'), (L_length, L_accel, L_stress))
L_EI     = new_scale('EI',     ('length', 'accel', 'stress'), (L_length, L_accel, L_stress))

print(1/L_load_L, 1/L_EI)

Portanto, a carga (força) por unidade de comprimento no modelo deve ser 28.87 vezes menor, enquanto a rigidez à flexão deve ser 28870 vezes menor. Aplicando as escala aos valores calculados para o protótipo tem-se:

In [ ]:
q  = 4400. * L_load_L
EI = 1.6e6 * L_EI

print(q, EI)

Inicialmente vamos definir uma seção transversal de alumínio que respeite o valor acima. Podemos, por exemplo, utilizar uma lâmina de seção retangular com altura de 5mm, deixando em aberto o valor da largura:

\begin{align*}
 EI &= E \; \frac{b h^3}{12} \\
 b  &= \frac{12 EI}{E h^3}
\end{align*}

Substituindo valores:

In [ ]:
b = 12*EI/(0.005**3)/7.1e10;    print(b)

Ou seja, a lâmina deve ter uma seção retângular de $5\times 75$mm. Considerando que a massa específica do alumínio é da ordem de 2700${\rm kg/m^3}$, o peso por unidade de comprimento desta lâmina é: 

In [ ]:
W = 2700*0.005*0.075*9.81;      print(W) 


Portando, é necessário acrescentar massa à lâmina, o que deve ser feito sem interferir na rigidez da seção transversal. Isso pode ser alcançado colando-se pequenos pedaços de chumbo, de modo a totalizar o valor requerido. A massa adicional a ser acrescentada resulta ser:

In [ ]:
m_add = q/9.81 - W;             print(m_add)

Como o vão em escala reduzida é de exatamente 1m, deve-se acrescentar um total de 5.6kg de chumbo distribuídos ao longo do comprimento do modelo, totalizando aproximadamente 15.6kg de massa total.
Observa-se que modelos reduzidos em escala de aceleração 1:1 geralmente resultam bastante flexíveis e pesados, mas é isso que se faz necessário para que as deformações por peso próprio respeitem a escala de comprimento.

Uma vez construído o modelo com estas características, os deslocamentos desejados podem ser então experimentalmente medidos. No caso deste exemplo em particular, existe uma fórmula teórica que permite o cálculo do deslocamento no centro do vão:

$$
w_{\rm max} = \frac{5}{384} \frac{q L^4}{EI}
$$

Substituindo-se valores para a escala do protótipo:

In [ ]:
w_max = (5/384)*4400*(10**4)/1.6e6;    print(w_max)

Enquanto para a escala do modelo:

In [ ]:
w_max = (5/384)*152.4*(1**4)/55.41;    print(w_max)

Ou seja, confirma-se que o deslocamento no centro está aproximadamente na escala 1:10, como pretendido.

### 2.3. Example: aeroelastic model of a slender tower  <a name="section_23"></a> 



### 2.4. Example: cable catenary  <a name="section_24"></a> 




<img src="resources/sag_tension.png" alt="sag_tension" width="480px"/>
